---
 - name: Check that the conda binary exists
   stat:
     path: "{{ miniforge.home }}/bin/mamba"
   register: stat_conda
   tags: conda

 - name: download miniconda mambaforge installer
   get_url:
     url: "https://github.com/conda-forge/miniforge/releases/download/{{ miniforge.version }}/Mambaforge-{{ miniforge.version }}-Linux-x86_64.sh"
     checksum: "sha256:{{ miniforge.sha256 }}"
     dest: "/tmp/miniforge.sh"
     force: false
     mode: 0755
   when: not stat_conda.stat.exists
   tags: conda

 - name: install miniforge
   become: yes
   shell:
     creates: "{{ miniforge.home }}/bin/conda"
     cmd: |
       /tmp/miniforge.sh -b -p "{{ miniforge.home }}"
   when: not stat_conda.stat.exists
   tags: conda

 - name: ensure conda.sh activated in shell
   become: yes
   file:
     src: "{{ miniforge.home }}/etc/profile.d/conda.sh"
     dest: "/etc/profile.d/conda.sh"
     state: link
   tags: conda

 - name: Ensure conda activate directory exists
   become: true
   file:
     path: "{{ miniforge.home }}/etc/conda/activate.d"
     state: directory
     mode: '0755'
   tags: conda

 - name: create conda configuration directory
   become: yes
   file:
     path: /etc/conda
     state: directory
   tags: conda

 - name: Remove implicit .condarc file installed by miniforge
   become: yes
   file:
     path: "{{ miniforge.home }}/.condarc"
     state: absent

 - name: Create default condarc for users
   become: yes
   copy:
     dest: /etc/conda/condarc
     mode: 644
     content: |
       channels:
         - conda-forge
       envs_dirs:
         - "~/.conda/envs"
       pkgs_dirs:
         - "~/.conda/pkgs"
   tags: conda
