name: "Vagrant (KVM) Tests"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-kvm:
    name: "KVM Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Check KVM Capabilities of CI"
        run: |
          sudo kvm-ok
